@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.accessToken}}

# @name authenticate
POST {{baseUrl}}/auth
Content-Type: application/json

{
  "email": "admin@crm.com",
  "password": "password"
}
###

# @name authenticate
POST {{baseUrl}}/auth
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "password123"
}
###

# @name register_salesperson
POST {{baseUrl}}/salespersons
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "John Doe 7",
  "email": "johndoe7@example.com",
  "password": "password123",
  "phone": "123-456-7890"
}
###


# @name register_client
POST {{baseUrl}}/clients
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Client 9",
  "email": "client9@example.com",
  "phone": "123-456-7890",
  "segment": "Retail"
}
###